#!/usr/bin/env ruby

def release(port)
  pid = `sudo lsof -iTCP -sTCP:LISTEN -n -P | grep #{port} | awk '{ print $2 }' | head -n 1`.strip
  `sudo kill -9 #{pid}` unless pid.empty?
end

release 4444   # Jekyll HTTPS
release 25_724 # Webapp reload
